{% set name = "types-MarkupSafe" %}
{% set version = "1.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-MarkupSafe-{{ version }}.tar.gz
  sha256: 85b3a872683d02aea3a5ac2a8ef590193c344092032f58457287fbf8e06711b1

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/markupsafe-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for MarkupSafe
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
